package Vue;

import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import static javax.swing.JOptionPane.showMessageDialog;

public class AjoutInterview extends javax.swing.JFrame {

    // Variables declaration - do not modify                     
    public javax.swing.JTextArea Jcontenue;
    public javax.swing.JTextField Jdomaine;
    public javax.swing.JTextField Jtitre;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> num_revue;
    /**
     * Creates new form home
     */
    public AjoutInterview() {
        initComponents();
        loadRevueNumbers();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutInterview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutInterview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutInterview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutInterview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutInterview().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Jtitre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Jdomaine = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jcontenue = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        num_revue = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DzVues  - Chef de rédaction ");

        jPanel1.setBackground(new java.awt.Color(20, 49, 9));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ajouter une interview");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 22, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 56, 787, 1));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Revue");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));



        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Domaine:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        Jtitre.setToolTipText("");
        Jtitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtitreActionPerformed(evt);
            }
        });
        jPanel1.add(Jtitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 677, 38));

        Jdomaine.setToolTipText("");
        Jdomaine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JdomaineActionPerformed(evt);
            }
        });
        jPanel1.add(Jdomaine, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 676, 38));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contenu:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        Jcontenue.setColumns(20);
        Jcontenue.setRows(5);
        jScrollPane1.setViewportView(Jcontenue);


        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 670, 232));

        jButton3.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jButton3.setText("Sauvegarder");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, -1, 41));

        num_revue.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        num_revue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        num_revue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_revueActionPerformed(evt);
            }
        });
        jPanel1.add(num_revue, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Titre:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void JtitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtitreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_JtitreActionPerformed

    private void JdomaineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JdomaineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JdomaineActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:

        // close the window and go back to the home page
        this.dispose();

    }//GEN-LAST:event_cancelButtonActionPerformed

    private void loadRevueNumbers() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3308/dzvues";
        String user = "root";
        String pass = "";
            Connection con = DriverManager.getConnection(url, user, pass);
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT num FROM revue");
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            while (rs.next()) {
                model.addElement(rs.getString("num"));
            }
            num_revue.setModel(model);
            con.close();
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String query;
        String titre = Jtitre.getText();
        String domaine = Jdomaine.getText();
        String contenue = Jcontenue.getText();
        String selectedRevueNumber = (String) num_revue.getSelectedItem();


        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

        String url = "jdbc:mysql://localhost:3308/dzvues";
        String user = "root";
        String pass = "";
            System.out.println("Ok");


            Connection con = DriverManager.getConnection(url, user, pass);
            Statement st = con.createStatement();

            if ("".equals(Jtitre.getText())) {

                JOptionPane.showMessageDialog(new JFrame(), "Titre is require", "Dialog", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(Jdomaine.getText())) {

                JOptionPane.showMessageDialog(new JFrame(), "Domaine is require", "Dialog", JOptionPane.ERROR_MESSAGE);
            }
             else {

                titre = Jtitre.getText();
                domaine = Jdomaine.getText();
                contenue = Jcontenue.getText();


                int idInterview = 0;
                query = "INSERT INTO interview (idInterview, titre, domaine, contenu, numeroRevue) " + "VALUES ('" + idInterview + "','" + titre + "','" + domaine + "','" + contenue + "','" + selectedRevueNumber + "')";
                st.executeUpdate(query);
                showMessageDialog(null, "Successfully registered.");
                con.close();
                this.dispose();
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void num_revueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_revueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_revueActionPerformed
    // End of variables declaration                   
}
